### ISSUE TITLE
Browser-based sign in

### ISSUE THREAD

**Issue by benconstantine39** [okta/okta-oidc-ios#330] opened 2022-01-11 18:02 UTC
After signing in via browser, the user can briefly see a system prompt (ie action sheet) to save the login to keychain but then it is dismissed due to the redirect that takes the user back to the app. Is there a way to wait for the user to finish interacting with that action sheet? Either way it looks odd to the user, not sure it there's a configuration option I missed or what

**Comment by mikenachbaur-okta** [comment] 2022-01-11 20:11
This unfortunately is a limitation of Apple's SDKs that many people in the industry are fighting with. There are a few issues online (such as [this one at StackOverflow](https://stackoverflow.com/a/65156341) and [this one at Apple's developer forums](https://developer.apple.com/forums/thread/127979)) that shows this is a common complaint.

This issue is a duplicate of #271 with some similar guidance.

One recommendation is to file an issue with Apple to emphasize that some improvements should be made to enable this feature.

**Closed** 2022-08-05 23:05 UTC
