### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by ajevans99** [okta/okta-oidc-ios#225] opened 2020-05-21 16:29 UTC
Are there any plans to support Swift Package Manager?

https://swift.org/package-manager/#conceptual-overview

**Comment by IldarAbdullin-okta** [comment] 2020-05-29 04:31
Hi @ajevans99 ,

Thanks for creating this ticket. This library is a great candidate for SPM since there are no pod dependencies on 3rd party libs. So, yes, we would like to add support of SPM in near future

Thanks,
Ildar

**Comment by sam-w** [comment] 2020-07-07 06:43
+1 to this please!

**Comment by IldarAbdullin-okta** [comment] 2020-07-09 21:43
Created story ticket in our internal bug tracking system. We will do our best to implement this in August

**Comment by lukenewman** [comment] 2020-09-07 20:25
https://github.com/okta/okta-oidc-ios/pull/237

**Comment by ryanthon** [comment] 2020-09-18 00:51
Any idea on when this will be pulled in?

**Comment by EricDobyns** [comment] 2020-09-18 00:52
^^

**Comment by IldarAbdullin-okta** [comment] 2020-09-18 01:44
On master. Tag: 3.9.1

**Comment by sam-w** [comment] 2020-09-21 02:44
@IldarAbdullin-okta I think this issue needs to be re-opened. SwiftPM is definitely not working for me (on Xcode 12 GM). There's a lot more work to do in this repo than just adding the `Package.swift` file. (see this WIP PR: https://github.com/okta/okta-oidc-ios/pull/245)

What I see when trying to pull in `master` with SwiftPM.
<img width="741" alt="Screen Shot 2020-09-21 at 12 43 04 pm" src="https://user-images.githubusercontent.com/8063477/93729502-132ee600-fc08-11ea-9a9b-4c62d3360cd8.png">

**Comment by sam-w** [comment] 2020-09-21 03:48
For anyone else following this thread and experiencing the same, see https://github.com/okta/okta-oidc-ios/pull/245 for a possible solution.

**Comment by IldarAbdullin-okta** [comment] 2020-09-21 05:05
I was too excited with the contribution that totally forgot to test it before merge, my bad. This project is multi-language and therefore require more complicated structure in `Package.swift`. On high level it should declare:
- Core library in Objective-C
- Swift part that uses Core as a dependency
This also require some restructure in files hierarchy as Swift wrapper also contains some Objective-C files. Also MacOS support adds some complexity

@sam-w , I've noticed that you opened contribution PR. Thanks for looking into this!

**Comment by sam-w** [comment] 2020-09-21 05:13
😂 fair enough @IldarAbdullin-okta. The PR I've opened doesn't get us all the way there, and I'm currently not able to spend any more time on this. Other contributions welcome

**Comment by IldarAbdullin-okta** [comment] 2020-09-22 00:37
I've brought this to the team's attention today. The decision was made that team will start looking into it next week!

**Comment by jcgonlop** [comment] 2020-10-16 16:28
Hey guys, could you give us an update on this issue? Is there any ETA when this will be fixed? We are currently working on migrating to SPM and this is kind of a blocker.

**Comment by IldarAbdullin-okta** [comment] 2020-10-20 23:08
Hi @jcgonlop ,

The decision was made to address SPM feature in November.
cc @lihaoli-okta 

Ildar

**Comment by Nonnus** [comment] 2020-10-30 10:44
+1 for SPM support

**Comment by mikenachbaur-okta** [comment] 2020-12-03 22:46
Swift Package Manager support was introduced in #254 and is available in the 3.9.3 release. If you have any problems with using SPM, please let us know.

**Comment by Antoine4011** [comment] 2021-01-04 17:45
Hello @mikenachbaur-okta, unfortunately I think I still have an issue with the integration. We're using `OktaOidc` through an other Swift Package, not directly in the final app. 

Everything builds fine but when launching the app : 
```dyld: Library not loaded: @rpath/OktaOidc.framework/OktaOidc
  Referenced from: /private/var/containers/Bundle/Application/EFD45359-65C4-4F46-ADEE-35DB72F3CE4E/Sample.app/Sample
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
(lldb) 
```

The only fix we found so far is to generate an xcframework. That's the chose Stripe made, I wonder if this why. https://github.com/stripe/stripe-ios/releases/tag/21.1.0

Any help would be appreciated 🙏

**Comment by mikenachbaur-okta** [comment] 2021-01-04 23:46
Interesting @Antoine4011, would you be able to share which package it is that's pulling OktaOidc in as a dependency?  I'll try to reproduce that locally here to see what we can do to solve this.

Thank you

**Comment by jinahadam** [comment] 2021-02-04 00:50
would love this, specially with the current state of Carthage.

**Comment by sjmadsen** [comment] 2021-04-19 18:40
I'm having the same problem as @Antoine4011, where the app builds fine, but crashes at launch with the `@rpath` error. In our case, the package that's pulling in OktaOidc is an internal Swift package that holds common logic across two of our apps.

**Closed** 2021-04-26 17:19 UTC
Labels: enhancement

**Comment by sjmadsen** [comment] 2021-05-03 14:59
Thanks for fixing this in `master`. It looks like the 3.10.2 release tag added last week excludes that commit. Was that intentional and do we need to wait for 3.10.3?

**Comment by oleggnidets-okta** [comment] 2021-05-05 07:46
@sjmadsen The issue was closed automatically by GitHub when the PR has been closed. 
We'll release the update soon.

**Comment by oleggnidets-okta** [comment] 2021-05-06 10:30
@sjmadsen Please, check out the [3.10.3](https://github.com/okta/okta-oidc-ios/releases/tag/3.10.3).
