### ISSUE TITLE
"Cookies are required" displayed after enabling cookies in safari settings.

### ISSUE THREAD

**Issue by dextertalbert** [okta/okta-oidc-ios#333] opened 2022-01-24 21:24 UTC
When a user has disabled the cookies in the iPhone/Safari settings, and has tried unsuccessfully to login to the app and then enables cookies again, the Okta Webview keeps displaying the “Cookies are required“ message.

**To Reproduce**
1. Go to Settings->Safari and _toggle on_ **Block All Cookies**
2. Attempt sign in authentication flow
3. You should now receive the "Cookies are required" error message.
4. Go to Settings->Safari and _toggle off_ **Block All Cookies**
5. Attempting authentication after unblocking cookies still results in a "Cookies are required" error message.

**Expected behavior**
After unblocking cookies the authentication flow should allow you to attempt to login.

**Screenshots**
![image](https://user-images.githubusercontent.com/33534462/150866092-dea917ce-b78f-4b33-915b-61fc9c662212.jpeg)

**Smartphone:**
 - Device: iPhone 12 Pro
 - OS: iOS 15.1.1
 - Browser: Safari
 - Okta Version: 3.10.8

**Additional context**
- Deleted host app and re-installed
- Cleared host app data

**Comment by aarongranick-okta** [comment] 2022-01-25 00:53
@dextertalbert Thank you for bringing this issue to our attention. I have created an internal issue OKTA-463498. Our engineers will investigate and follow up.

**Comment by mikenachbaur-okta** [comment] 2022-01-25 17:34
@dextertalbert I wasn't able to reproduce this problem on my end using the Okta Sign In Widget and the latest OIDC SDK version.  The Okta sign in widget itself doesn't appear to require cookies to function, so this might be some sort of conflict with the frontend side of your sign in process.

When configuring the OIDC client, are you using the `noSSO` flag?

To me, this seems like an iOS bug more than anything; if the problem is persisting after deleting the app and reinstalling it, this seems to be out of the scope of the OIDC SDK or your application, and more of an environment problem.

**Comment by dextertalbert** [comment] 2022-01-27 20:00
We are not using the `noSSO` flag. Oddly I have been unable to reproduce this issue today.

**Comment by mikenachbaur-okta** [comment] 2022-01-28 19:54
That's interesting @dextertalbert. So it does indeed sound to me like this is an iOS bug. If you don't mind, I'll close this ticket, but if you encounter this again, or if you figure out reproduction steps, please don't hesitate to reopen it.

**Closed by mikenachbaur-okta** 2022-01-28 19:54 UTC
