### ISSUE TITLE
Access token signature being truncated

### ISSUE THREAD

**Issue by fporcaro** [okta/okta-oidc-ios#278] opened 2021-03-19 16:10 UTC
When getting the access token from the OktaOidcStateManager, the signature portion of the jwt is being truncated.  If a token is requested through Postman with the same client details, the signature is the full length.

I can provide token examples as well as sample code if needed to to reproduce the problem.  We are using version 3.10.1

**Comment by mikenachbaur-okta** [comment] 2021-03-19 17:59
Thank you @fporcaro, this looks interesting. If you're able to provide an example or sample code, that would certainly help to narrow down the problem on my end. Either way I'll look into this shortly.

**Comment by mikenachbaur-okta** [comment] 2021-03-22 22:09
@fporcaro I'm not able to reproduce this locally; if you could provide some sample code, that would certainly help me find out where the issue is.

**Comment by fporcaro** [comment] 2021-03-23 01:17
Hey Mike, sorry I missed your earlier email.  I think it has something to
do with the access token being used from an OidcStateManager loaded from
the keychain.  I've seen it on and off for a few releases, but it is
difficult to pin down.  I'll see if I can put together a sample app that
replicates the problem.  If I remember correctly, it shows up when
installing a newer version of the application where there would be a token
that is unexpired but was saved perhaps.  Once I logout and fetch a new
token, all seems to be well.  But I will dig a little more first thing in
the morning to see if I can come up with a better way to reproduce it.  I
was hoping it would be one of those things that once you were looking at
it/for it, it would be obvious - so much for that :)

I'll report back soon.

**Comment by oleggnidets-okta** [comment] 2021-04-09 10:11
Hi @fporcaro,
Any updates on that?

**Comment by oleggnidets-okta** [comment] 2021-04-30 08:15
@fporcaro I close the issue as no updates on that for a long time. 
Please, feel free to reopen it if you still have the issue. 

Thanks for using Okta!

**Closed by oleggnidets-okta** 2021-04-30 08:15 UTC
Labels: question
