### ISSUE TITLE
No Browser Presented on 'My Mac (Designed for iPad)' Target

### ISSUE THREAD

**Issue by richardpiazza** [okta/okta-oidc-ios#319] opened 2021-11-09 19:42 UTC
Under these conditions:
* **iOS Application** using browser-based authentication
* **My Mac (Designed for iPad)** target _or_ using a TestFlight build on Apple Silicon hardware

calling `OktaOidc.signInWithBrowser(from:callback)` does not show a browser authentication page.

The same build while running on an iOS device (iPhone, iPad, iPod touch) works as expected.

Is there any documentation, work-around, or something that I am missing on how this should work when running an iOS application on Apple Silicon hardware?

**Comment by monde** [comment] 2021-11-09 22:03
Thanks @richardpiazza . @mikenachbaur-okta have you seen this before? Should I file a Jira on it?

**Comment by monde** [comment] 2021-11-09 22:24
Okta internal reference: [OKTA-445374](https://oktainc.atlassian.net/browse/OKTA-445374)

**Comment by mikenachbaur-okta** [comment] 2021-11-09 22:28
@richardpiazza I don't have access to an M1 Mac at the moment, but a colleague of mine is going to try reproducing this. I'll keep you posted.

**Comment by mikenachbaur-okta** [comment] 2021-11-10 17:52
Hi @richardpiazza, one of our engineers tried [our Browser sign-in sample project](https://github.com/okta/samples-ios/tree/master/browser-sign-in) on an M1 Mac with the "Designed for iPad" target, and she was able to get it running on an M1 Mac Mini just fine (the browser authentication page showed up and she was able to sign in).

There might be a configuration problem that could be affecting the SDK.  Can you try the above sample app to see if it works in your environment?

**Comment by richardpiazza** [comment] 2021-11-10 18:17
@mikenachbaur-okta I've tried the example project with the same configuration and URL Scheme that is being used within our iOS app. The following prompt shows when tapping the 'Sign In' button:
<img width="790" alt="AllowAuthPrompt" src="https://user-images.githubusercontent.com/1744463/141170191-7a82065a-2e96-4379-b6b7-f83c74059cbf.png">
After tapping 'Continue', nothing appears to happen either within the browser or the application.

* iOS Deployment Target (default): 12.0
* OS: macOS Monterey 12.0.1
* Safari: Version 15.1 (17612.2.9.1.20)

**Comment by mikenachbaur-okta** [comment] 2021-11-10 19:32
Hmm interesting @richardpiazza, does this same sample app work when targeting an iPhone or iPad?

**Comment by richardpiazza** [comment] 2021-11-10 19:37
@mikenachbaur-okta Good question... Just tested, and yes, when running on the iOS simulator and on an iPhone the same code presents a browser for authentication.

**Comment by mikenachbaur-okta** [comment] 2021-11-10 19:40
If you wouldn't mind testing one more thing @richardpiazza, can you disable ephemeral sessions (which controls the usage of the `noSSO` configuration property) and try on your Mac again? I'm trying to determine which code path is exhibiting this problem.

**Comment by richardpiazza** [comment] 2021-11-10 19:45
Sure... None of my previous tests uses that 'Ephemeral Session' toggle - it was always off. What's interesting though is that toggling it to the 'on' state and tapping 'Sign In', didn't produce the same safari authentication prompt as before.

<img width="820" alt="Screen Shot 2021-11-10 at 1 43 16 PM" src="https://user-images.githubusercontent.com/1744463/141182436-fcebf4f0-cee6-462b-8495-619d087455c0.png">

**Comment by mikenachbaur-okta** [comment] 2021-11-10 20:48
That prompt is shown to the user as a result of the ASWebAuthenticationSession requesting access to a user's shared browser cookies.

https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession/3237231-prefersephemeralwebbrowsersessio

With ephemeral sessions enabled, did the browser and sign-in screen work for you?

**Comment by richardpiazza** [comment] 2021-11-10 20:58
No... with ephemeral sessions enabled, nothing happened. The prompt above never showed, and nothing happened within the app nor system browser.

**Comment by mikenachbaur-okta** [comment] 2021-11-10 21:12
Alright, thank you for your troubleshooting steps @richardpiazza. We've filed a ticket internally for this, and I'll begin looking into this issue as soon as I can.

**Comment by richardpiazza** [comment] 2021-11-14 15:41
This may have been an issue with Safari itself... I completely quit Safari this weekend, and upon restarting I was presented with multiple authentication windows. The authentication on my Mac machine appears to be working once again.

**Comment by oleggnidets-okta** [comment] 2021-11-15 13:58
I would lie to link another issue on M1 for visibility. #301 
Thanks

**Comment by mikenachbaur-okta** [comment] 2021-11-15 17:18
Oh, interesting @richardpiazza. I came across [this post on the Apple developer forums](https://developer.apple.com/forums/thread/694465) that sounds similar to your issue. So perhaps this is a bug in macOS.

**Comment by mikenachbaur-okta** [comment] 2021-11-29 17:35
@richardpiazza Since this seems to be a platform bug, I'm going to close this ticket out. But if you find additional reproduction steps, or you encounter this again, please feel free to reopen it.

Thank you

**Closed by mikenachbaur-okta** 2021-11-29 17:35 UTC
